import { defineConfig } from "vite-plus";

export default defineConfig({
  test: {
    // Delegate to each package's own config — packages/auth carries the wasm
    // plugin + inline-deps setup that argon2id-wasm requires under vitest.
    projects: ["packages/auth"],
  },
  fmt: {
    ignorePatterns: [
      "**/dist/**",
      "**/node_modules/**",
      "**/_generated/**",
      "pnpm-lock.yaml",
      "**/uniwind-types.d.ts",
      // Generated by the TanStack Router plugin — it owns its contents.
      "**/routeTree.gen.ts",
    ],
  },
  lint: {
    ignorePatterns: [
      "**/dist/**",
      "**/node_modules/**",
      "**/_generated/**",
      // Generated by `next dev`/`next build` — Next.js owns its contents.
      "**/next-env.d.ts",
      // Generated by the TanStack Router plugin — it owns its contents.
      "**/routeTree.gen.ts",
    ],
    jsPlugins: ["@convex-dev/eslint-plugin"],
    overrides: [
      {
        files: ["**/convex/**/*.ts", "**/src/component/**/*.ts", "**/src/convex-runtime/**/*.ts"],
        rules: {
          "@convex-dev/no-old-registered-function-syntax": "error",
          "@convex-dev/require-args-validator": "error",
          "@convex-dev/explicit-table-ids": "error",
          "@convex-dev/import-wrong-runtime": "error",
          "@convex-dev/no-filter-in-query": "error",
          "@convex-dev/no-collect-in-query": "error",
          "@convex-dev/no-top-of-hour-crons": "warn",
          "@convex-dev/no-schema-import-cycle": "error",
          "@convex-dev/no-duplicate-indexes": "error",
          /*
           * no-process-env wants the typed `env` object from _generated/server,
           * which only exists in consumer codegen — this package ships runtime
           * source that must read deployment env vars via process.env.
           */
          "@convex-dev/no-process-env": "off",
          /*
           * require-access-control regex-matches calls like requireUser/checkAccess
           * in public functions; upstream ships it off and this repo enforces
           * auth inside handlers rather than by wrapper convention.
           */
          "@convex-dev/require-access-control": "off",
        },
      },
      {
        files: ["**/*.test.ts"],
        rules: {
          "@convex-dev/no-top-of-hour-crons": "off",
        },
      },
      /*
       * These schema files keep covered prefix indexes on purpose: the
       * by_X index serves creation-ordered first-N list endpoints
       * (listMembersByOrganization, listByUser, the api-key / webhook /
       * service-principal / org-invitation list queries) while the
       * covering index sorts by status/key/provider — repointing would
       * silently change page membership and order.
       * Kept: organization_roles.by_organization, organization_members
       * .by_user/.by_organization, organization_invitations.by_organization,
       * api_keys.by_organization/.by_owner_service,
       * service_principals.by_organization, auth_identities.by_user,
       * webhook_endpoints.by_organization, webhook_deliveries.by_endpoint.
       */
      {
        files: [
          "packages/auth/src/component/schema/apiKeys.ts",
          "packages/auth/src/component/schema/organizations.ts",
          "packages/auth/src/component/schema/servicePrincipals.ts",
          "packages/auth/src/component/schema/users.ts",
          "packages/auth/src/component/schema/webhooks.ts",
        ],
        rules: {
          "@convex-dev/no-duplicate-indexes": "off",
        },
      },
    ],
  },
  staged: {
    "*.{js,jsx,ts,tsx}": ["vp lint --fix", "vp fmt"],
    "*.{css,json,jsonc}": "vp fmt",
  },
});
