import { defineMeta } from "blume";

export default defineMeta({
  title: "Docs",
  pages: [
    "index",
    "concepts",
    "installation",
    "quickstart",
    "configuration",
    "server-api",
    "client",
    "email-password",
    "oauth",
    "two-factor",
    "magic-links",
    "email-otp",
    "organizations",
    "api-keys",
    "webhooks",
    "security",
    "production",
    "react-native",
    "better-auth-alternatives",
    "migrating-from-better-auth",
    "migrating-from-convex-dev-better-auth",
    "migrating-from-full-component",
    "better-auth-to-convex",
    "compatibility",
    "examples",
    "preflight",
    "testing",
    "motivation",
    "how-we-got-here",
    "convex-native-auth-strategy",
    "feature-gated-components",
  ],
});
